### ISSUE TITLE
No PSP predict kernels

### ISSUE THREAD

**Issue by rlaker** [astrospice/astrospice#25]
This is due to the website being blank https://sppgway.jhuapl.edu/lpredict_ephem.

Compare with the expected results for reconstructed kernels https://sppgway.jhuapl.edu/recon_ephem

Tried to fix in #24 but parfive does not download the files after this change.

This could be the cause of #22.

**Comment by rlaker** [comment]
Looks like https://sppgway.jhuapl.edu/lpredict_ephem works again, so modify to use the new link as back up

**Comment by STBadman** [comment]
Just wanted to bump this again - the sppgway links do not seem to be very stable for the PSP kernels, they've disappeared at least twice in the last couple of months and are not working at the time I'm writing this - I think using SPDF https://spdf.gsfc.nasa.gov/pub/data/psp/ephemeris/spice/ would be more stable and future proof. Using heliopy routines for trajectory reconstruction work because this is where heliopy accesses things from. 

@rlaker did your parfive issues in #24  get resolved?

**Comment by rlaker** [comment]
Parfive included a bug fix for #24 in [v2.0.0](https://github.com/Cadair/parfive/releases/tag/v2.0.0). I haven't tested it yet, but if it works, then we can update the requirements for this package. 

I was also thinking about having a fall back to an offline file, as it is quite annoying to not be able to just work with astrospice when not connected to the internet.
